spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: task_tracker_bot_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS task_tracker_bot_schema
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false

app:
  properties:
    uri: "https://api.telegram.org/bot"
    token: "${TELEGRAM_BOT_TOKEN}"
    sleep-update-listener: 1s
  messages:
    start: "Добро пожаловать. Введите команду /help чтобы узнать все команды бота"
    help: "Доступные команды:\n
            /add - Добавить новую задачу\n
            /view - Посмотреть все задачи\n
            /complete - Отметить выполненную задачу\n
            /delete - Удалить задачу\n
    "
    add-task:
      add-category: "Укажите категорию задачи"
      add-description: "Укажите описание задачи"
      complete-add: "Задача успешно добавлена"
    complete-task:
      process-complete: "Укажите номер задачи, которую вы выполнили"
      complete-success: "Поздравляю с выполнением задачи!"
    delete-task:
      process-delete: "Для того, чтобы удалить задачу, введите номер задачи"
      complete-delete: "Удаление успешно"
    error:
      add-errors:
        category-validate: "Нельзя ввести категорию, начинающуюся на '/'. Введите /help чтобы узнать все команды бота"
        category-save: "Не удалось сохранить категорию. Введите /help чтобы узнать все команды бота"
        description-validate: "Нельзя ввести описание задачи, которая начинается на '/'. Введите /help чтобы узнать все команды бота"
        description-save-user: "Возникла ошибка регистрации пользователя в системе. Введите /help чтобы узнать все команды бота"
        description-save-task: "Возникла ошибка сохранения задачи в систему. Введите /help чтобы узнать все команды бота"
      complete-errors:
        id-validate: "Ошибка! Вы ввели не число. Введите /help чтобы узнать все команды бота"
        db-delete: "Возникла ошибка удаления задачи. Введите /help чтобы узнать все команды бота"
      delete-errors:
        id-validate: "Ошибка! Вы ввели не число. Введите /help чтобы узнать все команды бота"
        db-delete: "Возникла ошибка удаления задачи. Введите /help чтобы узнать все команды бота"
      unknown-error: "Возникла неизвестная ошибка!"
    unknown: "Неизвестная команда. Введите команду /help чтобы узнать все команды бота"

