server:
  port:
    8081

app:
  core:
    baseUri: "http://localhost:8082"
  properties:
    uri: "https://api.telegram.org/bot"
    token: "${TELEGRAM_BOT_TOKEN}"
    sleep-update-listener: 1s
  messages:
    start: "Добро пожаловать. Введите команду /help чтобы узнать все команды бота"
    help: "Доступные команды:\n
            /add - Добавить новую задачу\n
            /view - Посмотреть все задачи\n
            /complete - Отметить выполненную задачу\n
            /delete - Удалить задачу\n
    "
    view: "Ваши задачи:"
    view-template: "Id задачи: %s\n
                  Категория задачи: %s\n
                  Описание задачи: %s\n \n 
    "
    add-task:
      add-category: "Укажите категорию задачи"
      add-description: "Укажите описание задачи"
      complete-add: "Задача успешно добавлена Введите /help чтобы узнать все команды бота"
    complete-task:
      process-complete: "Укажите номер задачи, которую вы выполнили"
      complete-success: "Поздравляю с выполнением задачи! Введите /help чтобы узнать все команды бота"
    delete-task:
      process-delete: "Для того, чтобы удалить задачу, введите номер задачи"
      complete-delete: "Удаление успешно. Введите /help чтобы узнать все команды бота"
    errors:
      add-errors:
        category-validate: "Нельзя ввести категорию, начинающуюся на '/'. Введите /help чтобы узнать все команды бота"
        category-save: "Не удалось сохранить категорию. Введите /help чтобы узнать все команды бота"
        description-validate: "Нельзя ввести описание задачи, которая начинается на '/'. Введите /help чтобы узнать все команды бота"
        description-save-task: "Возникла ошибка сохранения задачи в систему. Введите /help чтобы узнать все команды бота"
      view-errors:
        getting-tasks: "Возникла ошибка получения списка задач. Введите /help чтобы узнать все команды бота"
      complete-errors:
        db-delete: "Возникла ошибка удаления задачи. Введите /help чтобы узнать все команды бота"
      delete-errors:
        db-delete: "Возникла ошибка удаления задачи. Введите /help чтобы узнать все команды бота"
      id-validate-errors:
        not-a-number: "Ошибка! Вы ввели не число. Введите /help чтобы узнать все команды бота"
        task-not-exists: "Ошибка! У вас нет задачи с таким номером. Введите /help чтобы узнать все команды бота"
      unknown-error: "Возникла неизвестная ошибка! Введите /help чтобы узнать все команды бота"
    unknown: "Неизвестная команда. Введите команду /help чтобы узнать все команды бота"

